import "@/styles/globals.css";
import "@/styles/nav.css";
import "@/styles/footer.css";
import "@/styles/sidebar.css";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Layout from "@/components/Layout";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  const router = useRouter();

  useEffect(() => {
    document.title = `Swop Pay - ${
      router.pathname.split("/")[1] != ""
        ? router.pathname
            .split("/")[1]
            .toLowerCase()
            .replace(/\b[a-z]/g, function (e) {
              return e.toUpperCase();
            })
        : "Home"
    }`;
  }, [router]);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname.split("/")[1] != "" ? (
        <Layout>
          <Component {...pageProps} />
        </Layout>
      ) : (
        <Component {...pageProps} />
      )}
    </>
  );
}
