import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import Image from "next/image";
import useWindowDimensions from "../components/useWindowDimensions";

const Dashboard = () => {
  const { width } = useWindowDimensions();

  return (
    <>
      <Head>
        <title>Swop Pay - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        {width > 991 && <Sidebar />}
        <div className="main-container">
          <div className="dashboard-container">
            <div className="dashboard-home">
              <div className="dashboard-home-card1">
                <Image
                  src="/image/travis.png"
                  alt="travis"
                  height={66}
                  width={66}
                />
                <div className="dashboard-home-card1-inside">
                  <h5>Travis Herron</h5>
                  <p>$travisherron</p>
                  <div className="dashboard-home-card1-button">
                    <button>Copy</button>
                    <button>QR</button>
                  </div>
                  <h6>Charolotte, NC</h6>

                  <div className=""></div>
                </div>
              </div>
              <div className="dashboard-home-card2"></div>
              <div className="dashboard-home-card3"></div>
              <div className="dashboard-home-card4"></div>
              <div className="dashboard-home-card5"></div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Dashboard;
