import Footer from "@/components/Footer";
import MainNav from "@/components/MainNav";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Swop Pay - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainNav />
        <div className="banner-div-top">
          <div className="container banner-div-top-inside">
            <div className="row">
              <div className="col-6">
                <h1>Allow Your Company To Take Crypto Payment Easily Online</h1>
                <p>
                  Swop’s Flat Rectangle NFC’s are designed to be durable and
                  simple to Flat is great to put under any phone case(non-metal)
                  Users can app to program any of our NFC’s with the click of a
                  button. This profile to the NFC for easy sharing. You just tap
                  the NFC on any phone to share your digital business card,
                  microsite, crypto the possibilities are endless. Use the swop
                  app to.
                </p>
                <Link href="/">Login</Link>
              </div>
              <div className="col-6">
                <Image
                  src="/image/crypto-payment-mobile.png"
                  alt="crypto-payment-mobile"
                  height={868}
                  width={738}
                  id="crypto-payment-mobile"
                />
              </div>
            </div>
          </div>
        </div>
        <div className="container polygon-blockchain-div">
          <div className="row">
            <div className="col-6">
              <Image
                src="/image/polygon-matic-badge.png"
                alt="polygon-matic-badge"
                height={676}
                width={454}
                id="polygon-matic-badge"
              />
            </div>
            <div className="col-6 polygon-blockchain-content-out">
              <div className="polygon-blockchain-content">
                <h2>
                  Cut your payment cost by 90% using the Polygon Blockchain
                </h2>
                <p>
                  Swop’s Flat Rectangle NFC’s are designed to be durable and
                  simple to use. The Flat is great to put under any phone
                  case(non-metal) Users can download our app to program any of
                  our NFC’s with the click of a button. This will attach your
                  profile to the NFC for easy sharing. You just tap the NFC on
                  any compatible.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className=""></div>
        <Footer />
      </main>
    </>
  );
}
